[tool.poetry]
name = "aws_lambda_powertools"
version = "1.24.2"
description = "A suite of utilities for AWS Lambda functions to ease adopting best practices such as tracing, structured logging, custom metrics, batching, idempotency, feature flags, and more."
authors = ["Amazon Web Services"]
include = ["aws_lambda_powertools/py.typed", "THIRD-PARTY-LICENSES"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
repository="https://github.com/awslabs/aws-lambda-powertools-python"
readme = "README.md"
keywords = ["aws_lambda_powertools", "aws", "tracing", "logging", "lambda", "powertools", "feature_flags", "idempotency", "middleware"]
license = "MIT-0"

[tool.poetry.dependencies]
python = "^3.6.2"
aws-xray-sdk = "^2.8.0"
fastjsonschema = "^2.14.5"
boto3 = "^1.18"
jmespath = "^0.10.0"
pydantic = {version = "^1.8.2", optional = true }
email-validator = {version = "*", optional = true }

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^6.2"}
pytest = "^6.2.5"
black = "^22.1"
flake8 = "^4.0.1"
flake8-black = "^0.2.3"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.7.0"
flake8-debugger = "^4.0.0"
flake8-fixme = "^1.1.1"
flake8-isort = "^4.1.1"
flake8-variables-names = "^0.0.4"
isort = "^5.10.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.5.1"
pdoc3 = "^0.10.0"
pytest-asyncio = "^0.16.0"
bandit = "^1.7.1"
radon = "^5.1.0"
xenon = "^0.8.0"
flake8-eradicate = "^1.2.0"
flake8-bugbear = "^22.1.11"
mkdocs-git-revision-date-plugin = "^0.3.1"
mike = "^0.6.0"
mypy = "^0.931"
mkdocs-material = "^8.1.9"


[tool.poetry.extras]
pydantic = ["pydantic", "email-validator"]

[tool.coverage.run]
source = ["aws_lambda_powertools"]
omit = ["tests/*", "aws_lambda_powertools/exceptions/*", "aws_lambda_powertools/utilities/parser/types.py", "aws_lambda_powertools/utilities/jmespath_utils/envelopes.py"]
branch = true

[tool.coverage.html]
directory = "test_report"
title = "Lambda Powertools Test Coverage"

[tool.coverage.report]
fail_under = 90
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

	# Ignore type function overload
	"@overload",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip = "example"

[tool.black]
line-length = 120
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | example
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
testpaths = "./tests"
markers = "perf: marks perf tests to be deselected (deselect with '-m \"not perf\"')"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# NOTE
# As of now, Feb 2020, flake8 don't support pyproject
# For latest: https://github.com/flying-sheep/awesome-python-packaging
